//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Research.Connector.Language.LionBridge
{
    public partial class WizardLastStep
    {
        
        /// <summary>
        /// notificationMail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox tbnotificationmail;
        protected global::System.Web.UI.WebControls.TextBox tbstartdate;
        protected global::System.Web.UI.WebControls.TextBox tbdeliverydate;
        protected global::System.Web.UI.WebControls.DropDownList ddltasks;
        protected global::System.Web.UI.WebControls.DropDownList ddlsubtasks;
        protected global::System.Web.UI.WebControls.DropDownList ddluoms;
           
    }
}
